version: '3.6'
services:
  web:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    command: puma
    ports:
      - 3000:3000

  redis:
    image: 'redis:5-alpine'
    command: redis-server
    ports:
      - '6379:6379'

  sidekiq:
    depends_on:
      - 'redis'
    build: .
    command: sidekiq
    volumes:
      - '.:/app'

volumes:
  redis: